# Generated by Django 5.1.1 on 2024-09-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('current_price', models.FloatField(default=0.0)),
                ('price_change', models.FloatField(default=0.0)),
                ('current_volume', models.FloatField(default=0.0)),
                ('volume_change', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='api.ticker')),
            ],
        ),
    ]
