# Generated by Django 5.1.1 on 2024-09-22 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='current_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='current_volume',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='price_change',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='volume_change',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('volume', models.FloatField()),
                ('date', models.DateTimeField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='api.ticker')),
            ],
        ),
        migrations.DeleteModel(
            name='Current',
        ),
    ]
