# Generated by Django 5.1.1 on 2024-09-22 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ticker_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.ticker'),
        ),
    ]
