# Generated by Django 5.1.1 on 2024-09-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ticker_last_update_alter_history_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
