# Generated by Django 5.1.1 on 2024-09-22 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
