# Generated by Django 5.1.1 on 2024-09-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='price_change_per',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='volume_change_per',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
